// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bridge/v1/bridge.proto

package bridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Protocol int32

const (
	Message_PROTOCOL_UNSPECIFIED Message_Protocol = 0
	Message_PROTOCOL_TCP         Message_Protocol = 1
	Message_PROTOCOL_UDP         Message_Protocol = 2
)

// Enum value maps for Message_Protocol.
var (
	Message_Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
		2: "PROTOCOL_UDP",
	}
	Message_Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
		"PROTOCOL_UDP":         2,
	}
)

func (x Message_Protocol) Enum() *Message_Protocol {
	p := new(Message_Protocol)
	*p = x
	return p
}

func (x Message_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_v1_bridge_proto_enumTypes[0].Descriptor()
}

func (Message_Protocol) Type() protoreflect.EnumType {
	return &file_bridge_v1_bridge_proto_enumTypes[0]
}

func (x Message_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Protocol.Descriptor instead.
func (Message_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{0, 0}
}

// Message is the unit of communication through the bridge tunnel.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The address that is sending the message.
	Source *Message_Address `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// The intended target address on the destination.
	Dest *Message_Address `protobuf:"bytes,3,opt,name=dest,proto3" json:"dest,omitempty"`
	// The payload data being tunneled.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// Connection ID for multiplexing multiple connections over one tunnel.
	ConnectionId string `protobuf:"bytes,5,opt,name=connection_id,proto3" json:"connection_id,omitempty"`
	// Set to true when the connection should be closed.
	Close bool `protobuf:"varint,6,opt,name=close,proto3" json:"close,omitempty"`
	// Error message if something went wrong.
	Error         string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_bridge_v1_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSource() *Message_Address {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Message) GetDest() *Message_Address {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Message) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

func (x *Message) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Message_Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Address) Reset() {
	*x = Message_Address{}
	mi := &file_bridge_v1_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Address) ProtoMessage() {}

func (x *Message_Address) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Address.ProtoReflect.Descriptor instead.
func (*Message_Address) Descriptor() ([]byte, []int) {
	return file_bridge_v1_bridge_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Address) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Message_Address) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_bridge_v1_bridge_proto protoreflect.FileDescriptor

const file_bridge_v1_bridge_proto_rawDesc = "" +
	"\n" +
	"\x16bridge/v1/bridge.proto\x12\tbridge.v1\"\xcc\x02\n" +
	"\aMessage\x122\n" +
	"\x06source\x18\x02 \x01(\v2\x1a.bridge.v1.Message.AddressR\x06source\x12.\n" +
	"\x04dest\x18\x03 \x01(\v2\x1a.bridge.v1.Message.AddressR\x04dest\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12$\n" +
	"\rconnection_id\x18\x05 \x01(\tR\rconnection_id\x12\x14\n" +
	"\x05close\x18\x06 \x01(\bR\x05close\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x1a-\n" +
	"\aAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"H\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x02B\x95\x01\n" +
	"\rcom.bridge.v1B\vBridgeProtoP\x01Z2github.com/vercel/bridge/api/go/bridge/v1;bridgev1\xa2\x02\x03BXX\xaa\x02\tBridge.V1\xca\x02\tBridge\\V1\xe2\x02\x15Bridge\\V1\\GPBMetadata\xea\x02\n" +
	"Bridge::V1b\x06proto3"

var (
	file_bridge_v1_bridge_proto_rawDescOnce sync.Once
	file_bridge_v1_bridge_proto_rawDescData []byte
)

func file_bridge_v1_bridge_proto_rawDescGZIP() []byte {
	file_bridge_v1_bridge_proto_rawDescOnce.Do(func() {
		file_bridge_v1_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_v1_bridge_proto_rawDesc), len(file_bridge_v1_bridge_proto_rawDesc)))
	})
	return file_bridge_v1_bridge_proto_rawDescData
}

var file_bridge_v1_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bridge_v1_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bridge_v1_bridge_proto_goTypes = []any{
	(Message_Protocol)(0),   // 0: bridge.v1.Message.Protocol
	(*Message)(nil),         // 1: bridge.v1.Message
	(*Message_Address)(nil), // 2: bridge.v1.Message.Address
}
var file_bridge_v1_bridge_proto_depIdxs = []int32{
	2, // 0: bridge.v1.Message.source:type_name -> bridge.v1.Message.Address
	2, // 1: bridge.v1.Message.dest:type_name -> bridge.v1.Message.Address
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bridge_v1_bridge_proto_init() }
func file_bridge_v1_bridge_proto_init() {
	if File_bridge_v1_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_v1_bridge_proto_rawDesc), len(file_bridge_v1_bridge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bridge_v1_bridge_proto_goTypes,
		DependencyIndexes: file_bridge_v1_bridge_proto_depIdxs,
		EnumInfos:         file_bridge_v1_bridge_proto_enumTypes,
		MessageInfos:      file_bridge_v1_bridge_proto_msgTypes,
	}.Build()
	File_bridge_v1_bridge_proto = out.File
	file_bridge_v1_bridge_proto_goTypes = nil
	file_bridge_v1_bridge_proto_depIdxs = nil
}
