// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/administrator.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bridge/v1/administrator.proto.
 */
export const file_bridge_v1_administrator = /*@__PURE__*/
  fileDesc("Ch1icmlkZ2UvdjEvYWRtaW5pc3RyYXRvci5wcm90bxIJYnJpZGdlLnYxIpwBChNDcmVhdGVCcmlkZ2VSZXF1ZXN0EhwKCWRldmljZV9pZBgBIAEoCVIJZGV2aWNlX2lkEiwKEXNvdXJjZV9kZXBsb3ltZW50GAIgASgJUhFzb3VyY2VfZGVwbG95bWVudBIqChBzb3VyY2VfbmFtZXNwYWNlGAMgASgJUhBzb3VyY2VfbmFtZXNwYWNlEg0KBWZvcmNlGAQgASgIIu0BChRDcmVhdGVCcmlkZ2VSZXNwb25zZRIRCgluYW1lc3BhY2UYASABKAkSGgoIcG9kX25hbWUYAiABKAlSCHBvZF9uYW1lEgwKBHBvcnQYAyABKAUSKAoPZGVwbG95bWVudF9uYW1lGAQgASgJUg9kZXBsb3ltZW50X25hbWUSPgoIZW52X3ZhcnMYBSADKAsyLC5icmlkZ2UudjEuQ3JlYXRlQnJpZGdlUmVzcG9uc2UuRW52VmFyc0VudHJ5Gi4KDEVudlZhcnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIjIKEkxpc3RCcmlkZ2VzUmVxdWVzdBIcCglkZXZpY2VfaWQYASABKAlSCWRldmljZV9pZCLHAQoKQnJpZGdlSW5mbxIcCglkZXZpY2VfaWQYASABKAlSCWRldmljZV9pZBIsChFzb3VyY2VfZGVwbG95bWVudBgCIAEoCVIRc291cmNlX2RlcGxveW1lbnQSKgoQc291cmNlX25hbWVzcGFjZRgDIAEoCVIQc291cmNlX25hbWVzcGFjZRIRCgluYW1lc3BhY2UYBCABKAkSHgoKY3JlYXRlZF9hdBgFIAEoCVIKY3JlYXRlZF9hdBIOCgZzdGF0dXMYBiABKAkiPQoTTGlzdEJyaWRnZXNSZXNwb25zZRImCgdicmlkZ2VzGAEgAygLMhUuYnJpZGdlLnYxLkJyaWRnZUluZm8iYQoTRGVsZXRlQnJpZGdlUmVxdWVzdBIcCglkZXZpY2VfaWQYASABKAlSCWRldmljZV9pZBIsChFzb3VyY2VfZGVwbG95bWVudBgCIAEoCVIRc291cmNlX2RlcGxveW1lbnQiFgoURGVsZXRlQnJpZGdlUmVzcG9uc2UyhgIKFEFkbWluaXN0cmF0b3JTZXJ2aWNlEk8KDENyZWF0ZUJyaWRnZRIeLmJyaWRnZS52MS5DcmVhdGVCcmlkZ2VSZXF1ZXN0Gh8uYnJpZGdlLnYxLkNyZWF0ZUJyaWRnZVJlc3BvbnNlEkwKC0xpc3RCcmlkZ2VzEh0uYnJpZGdlLnYxLkxpc3RCcmlkZ2VzUmVxdWVzdBoeLmJyaWRnZS52MS5MaXN0QnJpZGdlc1Jlc3BvbnNlEk8KDERlbGV0ZUJyaWRnZRIeLmJyaWRnZS52MS5EZWxldGVCcmlkZ2VSZXF1ZXN0Gh8uYnJpZGdlLnYxLkRlbGV0ZUJyaWRnZVJlc3BvbnNlQpwBCg1jb20uYnJpZGdlLnYxQhJBZG1pbmlzdHJhdG9yUHJvdG9QAVoyZ2l0aHViLmNvbS92ZXJjZWwvYnJpZGdlL2FwaS9nby9icmlkZ2UvdjE7YnJpZGdldjGiAgNCWFiqAglCcmlkZ2UuVjHKAglCcmlkZ2VcVjHiAhVCcmlkZ2VcVjFcR1BCTWV0YWRhdGHqAgpCcmlkZ2U6OlYxYgZwcm90bzM");

/**
 * Describes the message bridge.v1.CreateBridgeRequest.
 * Use `create(CreateBridgeRequestSchema)` to create a new message.
 */
export const CreateBridgeRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 0);

/**
 * Describes the message bridge.v1.CreateBridgeResponse.
 * Use `create(CreateBridgeResponseSchema)` to create a new message.
 */
export const CreateBridgeResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 1);

/**
 * Describes the message bridge.v1.ListBridgesRequest.
 * Use `create(ListBridgesRequestSchema)` to create a new message.
 */
export const ListBridgesRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 2);

/**
 * Describes the message bridge.v1.BridgeInfo.
 * Use `create(BridgeInfoSchema)` to create a new message.
 */
export const BridgeInfoSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 3);

/**
 * Describes the message bridge.v1.ListBridgesResponse.
 * Use `create(ListBridgesResponseSchema)` to create a new message.
 */
export const ListBridgesResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 4);

/**
 * Describes the message bridge.v1.DeleteBridgeRequest.
 * Use `create(DeleteBridgeRequestSchema)` to create a new message.
 */
export const DeleteBridgeRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 5);

/**
 * Describes the message bridge.v1.DeleteBridgeResponse.
 * Use `create(DeleteBridgeResponseSchema)` to create a new message.
 */
export const DeleteBridgeResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 6);

/**
 * AdministratorService manages bridge lifecycle in a Kubernetes cluster.
 *
 * @generated from service bridge.v1.AdministratorService
 */
export const AdministratorService = /*@__PURE__*/
  serviceDesc(file_bridge_v1_administrator, 0);

