// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/administrator.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bridge/v1/administrator.proto.
 */
export const file_bridge_v1_administrator = /*@__PURE__*/
  fileDesc("Ch1icmlkZ2UvdjEvYWRtaW5pc3RyYXRvci5wcm90bxIJYnJpZGdlLnYxIpwBChNDcmVhdGVCcmlkZ2VSZXF1ZXN0EhwKCWRldmljZV9pZBgBIAEoCVIJZGV2aWNlX2lkEiwKEXNvdXJjZV9kZXBsb3ltZW50GAIgASgJUhFzb3VyY2VfZGVwbG95bWVudBIqChBzb3VyY2VfbmFtZXNwYWNlGAMgASgJUhBzb3VyY2VfbmFtZXNwYWNlEg0KBWZvcmNlGAQgASgIIlMKFENyZWF0ZUJyaWRnZVJlc3BvbnNlEhEKCW5hbWVzcGFjZRgBIAEoCRIaCghwb2RfbmFtZRgCIAEoCVIIcG9kX25hbWUSDAoEcG9ydBgDIAEoBSIyChJMaXN0QnJpZGdlc1JlcXVlc3QSHAoJZGV2aWNlX2lkGAEgASgJUglkZXZpY2VfaWQixwEKCkJyaWRnZUluZm8SHAoJZGV2aWNlX2lkGAEgASgJUglkZXZpY2VfaWQSLAoRc291cmNlX2RlcGxveW1lbnQYAiABKAlSEXNvdXJjZV9kZXBsb3ltZW50EioKEHNvdXJjZV9uYW1lc3BhY2UYAyABKAlSEHNvdXJjZV9uYW1lc3BhY2USEQoJbmFtZXNwYWNlGAQgASgJEh4KCmNyZWF0ZWRfYXQYBSABKAlSCmNyZWF0ZWRfYXQSDgoGc3RhdHVzGAYgASgJIj0KE0xpc3RCcmlkZ2VzUmVzcG9uc2USJgoHYnJpZGdlcxgBIAMoCzIVLmJyaWRnZS52MS5CcmlkZ2VJbmZvImEKE0RlbGV0ZUJyaWRnZVJlcXVlc3QSHAoJZGV2aWNlX2lkGAEgASgJUglkZXZpY2VfaWQSLAoRc291cmNlX2RlcGxveW1lbnQYAiABKAlSEXNvdXJjZV9kZXBsb3ltZW50IhYKFERlbGV0ZUJyaWRnZVJlc3BvbnNlMoYCChRBZG1pbmlzdHJhdG9yU2VydmljZRJPCgxDcmVhdGVCcmlkZ2USHi5icmlkZ2UudjEuQ3JlYXRlQnJpZGdlUmVxdWVzdBofLmJyaWRnZS52MS5DcmVhdGVCcmlkZ2VSZXNwb25zZRJMCgtMaXN0QnJpZGdlcxIdLmJyaWRnZS52MS5MaXN0QnJpZGdlc1JlcXVlc3QaHi5icmlkZ2UudjEuTGlzdEJyaWRnZXNSZXNwb25zZRJPCgxEZWxldGVCcmlkZ2USHi5icmlkZ2UudjEuRGVsZXRlQnJpZGdlUmVxdWVzdBofLmJyaWRnZS52MS5EZWxldGVCcmlkZ2VSZXNwb25zZUKiAQoNY29tLmJyaWRnZS52MUISQWRtaW5pc3RyYXRvclByb3RvUAFaOGdpdGh1Yi5jb20vdmVyY2VsLWVkZGllL2JyaWRnZS9hcGkvZ28vYnJpZGdlL3YxO2JyaWRnZXYxogIDQlhYqgIJQnJpZGdlLlYxygIJQnJpZGdlXFYx4gIVQnJpZGdlXFYxXEdQQk1ldGFkYXRh6gIKQnJpZGdlOjpWMWIGcHJvdG8z");

/**
 * Describes the message bridge.v1.CreateBridgeRequest.
 * Use `create(CreateBridgeRequestSchema)` to create a new message.
 */
export const CreateBridgeRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 0);

/**
 * Describes the message bridge.v1.CreateBridgeResponse.
 * Use `create(CreateBridgeResponseSchema)` to create a new message.
 */
export const CreateBridgeResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 1);

/**
 * Describes the message bridge.v1.ListBridgesRequest.
 * Use `create(ListBridgesRequestSchema)` to create a new message.
 */
export const ListBridgesRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 2);

/**
 * Describes the message bridge.v1.BridgeInfo.
 * Use `create(BridgeInfoSchema)` to create a new message.
 */
export const BridgeInfoSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 3);

/**
 * Describes the message bridge.v1.ListBridgesResponse.
 * Use `create(ListBridgesResponseSchema)` to create a new message.
 */
export const ListBridgesResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 4);

/**
 * Describes the message bridge.v1.DeleteBridgeRequest.
 * Use `create(DeleteBridgeRequestSchema)` to create a new message.
 */
export const DeleteBridgeRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 5);

/**
 * Describes the message bridge.v1.DeleteBridgeResponse.
 * Use `create(DeleteBridgeResponseSchema)` to create a new message.
 */
export const DeleteBridgeResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_administrator, 6);

/**
 * AdministratorService manages bridge lifecycle in a Kubernetes cluster.
 *
 * @generated from service bridge.v1.AdministratorService
 */
export const AdministratorService = /*@__PURE__*/
  serviceDesc(file_bridge_v1_administrator, 0);

