// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/bridge.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bridge/v1/bridge.proto.
 */
export const file_bridge_v1_bridge = /*@__PURE__*/
  fileDesc("ChZicmlkZ2UvdjEvYnJpZGdlLnByb3RvEglicmlkZ2UudjEiNAoQU2VydmVyQ29ubmVjdGlvbhIgCgtzYW5kYm94X3VybBgBIAEoCVILc2FuZGJveF91cmwi0QQKB01lc3NhZ2USOgoMcmVnaXN0cmF0aW9uGAEgASgLMh8uYnJpZGdlLnYxLk1lc3NhZ2UuUmVnaXN0cmF0aW9uSACIAQESKgoGc291cmNlGAIgASgLMhouYnJpZGdlLnYxLk1lc3NhZ2UuQWRkcmVzcxIoCgRkZXN0GAMgASgLMhouYnJpZGdlLnYxLk1lc3NhZ2UuQWRkcmVzcxIMCgRkYXRhGAQgASgMEiQKDWNvbm5lY3Rpb25faWQYBSABKAlSDWNvbm5lY3Rpb25faWQSDQoFY2xvc2UYBiABKAgSDQoFZXJyb3IYByABKAkaIwoHQWRkcmVzcxIKCgJpcBgBIAEoCRIMCgRwb3J0GAIgASgFGuEBCgxSZWdpc3RyYXRpb24SJAoNZGVwbG95bWVudF9pZBgBIAEoCVINZGVwbG95bWVudF9pZBIcCglpc19zZXJ2ZXIYAiABKAhSCWlzX3NlcnZlchItCghwcm90b2NvbBgDIAEoDjIbLmJyaWRnZS52MS5NZXNzYWdlLlByb3RvY29sEiIKDGZ1bmN0aW9uX3VybBgEIAEoCVIMZnVuY3Rpb25fdXJsEjoKGHByb3RlY3Rpb25fYnlwYXNzX3NlY3JldBgFIAEoCVIYcHJvdGVjdGlvbl9ieXBhc3Nfc2VjcmV0IkgKCFByb3RvY29sEhgKFFBST1RPQ09MX1VOU1BFQ0lGSUVEEAASEAoMUFJPVE9DT0xfVENQEAESEAoMUFJPVE9DT0xfVURQEAJCDwoNX3JlZ2lzdHJhdGlvbkKbAQoNY29tLmJyaWRnZS52MUILQnJpZGdlUHJvdG9QAVo4Z2l0aHViLmNvbS92ZXJjZWwtZWRkaWUvYnJpZGdlL2FwaS9nby9icmlkZ2UvdjE7YnJpZGdldjGiAgNCWFiqAglCcmlkZ2UuVjHKAglCcmlkZ2VcVjHiAhVCcmlkZ2VcVjFcR1BCTWV0YWRhdGHqAgpCcmlkZ2U6OlYxYgZwcm90bzM");

/**
 * Describes the message bridge.v1.ServerConnection.
 * Use `create(ServerConnectionSchema)` to create a new message.
 */
export const ServerConnectionSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 0);

/**
 * Describes the message bridge.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 1);

/**
 * Describes the message bridge.v1.Message.Address.
 * Use `create(Message_AddressSchema)` to create a new message.
 */
export const Message_AddressSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 1, 0);

/**
 * Describes the message bridge.v1.Message.Registration.
 * Use `create(Message_RegistrationSchema)` to create a new message.
 */
export const Message_RegistrationSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 1, 1);

/**
 * Describes the enum bridge.v1.Message.Protocol.
 */
export const Message_ProtocolSchema = /*@__PURE__*/
  enumDesc(file_bridge_v1_bridge, 1, 0);

/**
 * @generated from enum bridge.v1.Message.Protocol
 */
export const Message_Protocol = /*@__PURE__*/
  tsEnum(Message_ProtocolSchema);

