// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/bridge.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bridge/v1/bridge.proto.
 */
export const file_bridge_v1_bridge = /*@__PURE__*/
  fileDesc("ChZicmlkZ2UvdjEvYnJpZGdlLnByb3RvEglicmlkZ2UudjEiNAoQU2VydmVyQ29ubmVjdGlvbhIgCgtzYW5kYm94X3VybBgBIAEoCVILc2FuZGJveF91cmwitQQKB01lc3NhZ2USOgoMcmVnaXN0cmF0aW9uGAEgASgLMh8uYnJpZGdlLnYxLk1lc3NhZ2UuUmVnaXN0cmF0aW9uSACIAQESKgoGc291cmNlGAIgASgLMhouYnJpZGdlLnYxLk1lc3NhZ2UuQWRkcmVzcxIoCgRkZXN0GAMgASgLMhouYnJpZGdlLnYxLk1lc3NhZ2UuQWRkcmVzcxIMCgRkYXRhGAQgASgMEiQKDWNvbm5lY3Rpb25faWQYBSABKAlSDWNvbm5lY3Rpb25faWQSDQoFY2xvc2UYBiABKAgSDQoFZXJyb3IYByABKAkaIwoHQWRkcmVzcxIKCgJpcBgBIAEoCRIMCgRwb3J0GAIgASgFGsUBCgxSZWdpc3RyYXRpb24SJAoNZGVwbG95bWVudF9pZBgBIAEoCVINZGVwbG95bWVudF9pZBIcCglpc19zZXJ2ZXIYAiABKAhSCWlzX3NlcnZlchItCghwcm90b2NvbBgDIAEoDjIbLmJyaWRnZS52MS5NZXNzYWdlLlByb3RvY29sEiIKDGZ1bmN0aW9uX3VybBgEIAEoCVIMZnVuY3Rpb25fdXJsEh4KCm9pZGNfdG9rZW4YBSABKAlSCm9pZGNfdG9rZW4iSAoIUHJvdG9jb2wSGAoUUFJPVE9DT0xfVU5TUEVDSUZJRUQQABIQCgxQUk9UT0NPTF9UQ1AQARIQCgxQUk9UT0NPTF9VRFAQAkIPCg1fcmVnaXN0cmF0aW9uQpsBCg1jb20uYnJpZGdlLnYxQgtCcmlkZ2VQcm90b1ABWjhnaXRodWIuY29tL3ZlcmNlbC1lZGRpZS9icmlkZ2UvYXBpL2dvL2JyaWRnZS92MTticmlkZ2V2MaICA0JYWKoCCUJyaWRnZS5WMcoCCUJyaWRnZVxWMeICFUJyaWRnZVxWMVxHUEJNZXRhZGF0YeoCCkJyaWRnZTo6VjFiBnByb3RvMw");

/**
 * Describes the message bridge.v1.ServerConnection.
 * Use `create(ServerConnectionSchema)` to create a new message.
 */
export const ServerConnectionSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 0);

/**
 * Describes the message bridge.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 1);

/**
 * Describes the message bridge.v1.Message.Address.
 * Use `create(Message_AddressSchema)` to create a new message.
 */
export const Message_AddressSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 1, 0);

/**
 * Describes the message bridge.v1.Message.Registration.
 * Use `create(Message_RegistrationSchema)` to create a new message.
 */
export const Message_RegistrationSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_bridge, 1, 1);

/**
 * Describes the enum bridge.v1.Message.Protocol.
 */
export const Message_ProtocolSchema = /*@__PURE__*/
  enumDesc(file_bridge_v1_bridge, 1, 0);

/**
 * @generated from enum bridge.v1.Message.Protocol
 */
export const Message_Protocol = /*@__PURE__*/
  tsEnum(Message_ProtocolSchema);

