// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file bridge/v1/proxy.proto (package bridge.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bridge/v1/proxy.proto.
 */
export const file_bridge_v1_proxy = /*@__PURE__*/
  fileDesc("ChVicmlkZ2UvdjEvcHJveHkucHJvdG8SCWJyaWRnZS52MSIqChZQcm94eVJlc29sdmVETlNSZXF1ZXN0EhAKCGhvc3RuYW1lGAEgASgJIjsKF1Byb3h5UmVzb2x2ZUROU1Jlc3BvbnNlEhEKCWFkZHJlc3NlcxgBIAMoCRINCgVlcnJvchgCIAEoCSIpCg1UdW5uZWxBZGRyZXNzEgoKAmlwGAEgASgJEgwKBHBvcnQYAiABKAUi2AEKFFR1bm5lbE5ldHdvcmtNZXNzYWdlEigKBnNvdXJjZRgBIAEoCzIYLmJyaWRnZS52MS5UdW5uZWxBZGRyZXNzEiYKBGRlc3QYAiABKAsyGC5icmlkZ2UudjEuVHVubmVsQWRkcmVzcxIkCg1jb25uZWN0aW9uX2lkGAMgASgJUg1jb25uZWN0aW9uX2lkEgwKBGRhdGEYBCABKAwSKwoIcHJvdG9jb2wYBSABKA4yGS5icmlkZ2UudjEuVHVubmVsUHJvdG9jb2wSDQoFZXJyb3IYBiABKAkqYwoOVHVubmVsUHJvdG9jb2wSHwobVFVOTkVMX1BST1RPQ09MX1VOU1BFQ0lGSUVEEAASFwoTVFVOTkVMX1BST1RPQ09MX1RDUBABEhcKE1RVTk5FTF9QUk9UT0NPTF9VRFAQAjLFAQoSQnJpZGdlUHJveHlTZXJ2aWNlElgKD1Jlc29sdmVETlNRdWVyeRIhLmJyaWRnZS52MS5Qcm94eVJlc29sdmVETlNSZXF1ZXN0GiIuYnJpZGdlLnYxLlByb3h5UmVzb2x2ZUROU1Jlc3BvbnNlElUKDVR1bm5lbE5ldHdvcmsSHy5icmlkZ2UudjEuVHVubmVsTmV0d29ya01lc3NhZ2UaHy5icmlkZ2UudjEuVHVubmVsTmV0d29ya01lc3NhZ2UoATABQpQBCg1jb20uYnJpZGdlLnYxQgpQcm94eVByb3RvUAFaMmdpdGh1Yi5jb20vdmVyY2VsL2JyaWRnZS9hcGkvZ28vYnJpZGdlL3YxO2JyaWRnZXYxogIDQlhYqgIJQnJpZGdlLlYxygIJQnJpZGdlXFYx4gIVQnJpZGdlXFYxXEdQQk1ldGFkYXRh6gIKQnJpZGdlOjpWMWIGcHJvdG8z");

/**
 * Describes the message bridge.v1.ProxyResolveDNSRequest.
 * Use `create(ProxyResolveDNSRequestSchema)` to create a new message.
 */
export const ProxyResolveDNSRequestSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 0);

/**
 * Describes the message bridge.v1.ProxyResolveDNSResponse.
 * Use `create(ProxyResolveDNSResponseSchema)` to create a new message.
 */
export const ProxyResolveDNSResponseSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 1);

/**
 * Describes the message bridge.v1.TunnelAddress.
 * Use `create(TunnelAddressSchema)` to create a new message.
 */
export const TunnelAddressSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 2);

/**
 * Describes the message bridge.v1.TunnelNetworkMessage.
 * Use `create(TunnelNetworkMessageSchema)` to create a new message.
 */
export const TunnelNetworkMessageSchema = /*@__PURE__*/
  messageDesc(file_bridge_v1_proxy, 3);

/**
 * Describes the enum bridge.v1.TunnelProtocol.
 */
export const TunnelProtocolSchema = /*@__PURE__*/
  enumDesc(file_bridge_v1_proxy, 0);

/**
 * @generated from enum bridge.v1.TunnelProtocol
 */
export const TunnelProtocol = /*@__PURE__*/
  tsEnum(TunnelProtocolSchema);

/**
 * BridgeProxyService runs in-cluster and provides DNS resolution and network
 * tunneling to the local bridge intercept client over gRPC.
 *
 * @generated from service bridge.v1.BridgeProxyService
 */
export const BridgeProxyService = /*@__PURE__*/
  serviceDesc(file_bridge_v1_proxy, 0);

